export const Users = [
    {
        id:1,
        profilePicture: "assets/person/xiaozhan.jpeg",
        username: "Xiao Zhan",
    },
    {
        id:2,
        profilePicture: "assets/person/bailu.jpeg",
        username: "Bai Lu",
    },
    {
        id:3,
        profilePicture: "assets/person/hejiong.jpg",
        username: "He Jiong",
    },
    {
        id:4,
        profilePicture: "assets/person/zhouyiran.jpg",
        username: "Zhou Yiran",
    },
    {
        id:5,
        profilePicture: "assets/person/xiena.jpeg",
        username: "Xie Na",
    },
    {
        id:6,
        profilePicture: "assets/person/shenyue.jpeg",
        username: "Shen Yue",
    },
    {
        id:7,
        profilePicture: "assets/person/wangyibo.jpeg",
        username: "Wang Yibo",
    },
    {
        id:8,
        profilePicture: "assets/person/luhan.jpeg",
        username: "Luhan",
    },
    {
        id:9,
        profilePicture: "assets/person/zhaoliying2.jpeg",
        username: "Zhao Liying",
    },
    {
        id:10,
        profilePicture: "assets/person/zhangyixing.jpeg",
        username: "Zhang Yi Xing",
    },
    {
        id:11,
        profilePicture: "assets/person/qinxiaoxian.jpg",
        username: "Qin Xiao Xian",
    },
    {
        id:12,
        profilePicture: "assets/person/zhaolusi.jpeg",
        username: "Zhao Lusi",
    },
];
    
export const Posts = [
    {
        id: 1,
        desc: "What a stunning!",
        photo: "assets/post/1.png",
        date: "5 mins ago",
        userId: 1,
        like: 3245156,
        comment: 94352,
    },
    {
        id: 2,
        desc: "Let's watch Keep Running this Saturday...",
        photo: "assets/post/2.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 22345,
        comment: 1256,
    },
    {
        id: 3,
        desc: "Irreplacable memories...",
        photo: "assets/post/3.jpeg",
        date: "1 hour ago",
        userId: 3,
        like: 61123,
        comment: 2566,
    },
    {
        id: 4,
        photo: "assets/post/4.jpeg",
        date: "4 hours ago",
        userId: 4,
        like: 13452,
        comment: 3345,
    },
    {
        id: 5,
        photo: "assets/post/5.jpg",
        date: "5 hours ago",
        userId: 5,
        like: 23345,
        comment: 1534,
    },
    {
        id: 6,
        desc: "Shooting finished today! Everyone did the great job.",
        photo: "assets/post/6.jpeg",
        date: "1 day ago",
        userId: 6,
        like: 8723,
        comment: 634,
    },
    {
        id: 7,
        desc: "Hi everyone, I am coming back as a idol Wang Yibo.",
        photo: "assets/post/7.jpg",
        date: "2 days ago",
        userId: 7,
        like: 52452,
        comment: 3234,
    },
    {
        id: 8,
        photo: "assets/post/8.jpg",
        desc: "A huge thank to my yellow ocean.",
        date: "3 days ago",
        userId: 8,
        like: 1587,
        comment: 123,
    },
    {
        id: 9,
        desc: "Hello, Xu Ban Xia!",
        photo: "assets/post/9.jpg",
        date: "5 days ago",
        userId: 9,
        like: 11345,
        comment: 2356,
    },
    {
        id: 10,
        photo: "assets/post/10.jpg",
        date: "1 week ago",
        userId: 10,
        like: 10344,
        comment: 1254,
    },
    {
        id: 11,
        photo: "assets/post/11.png",
        date: "1 week ago",
        userId: 11,
        like: 14534,
        comment: 1278,
    },
    {
        id: 12,
        desc: "Tell me your opinion on the drama...",
        photo: "assets/post/12.jpeg",
        date: "1 week ago",
        userId: 12,
        like: 14545,
        comment: 3434,
    },
];